/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arduinolcd;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author Anurag
 */
public class ArduinoLCD extends javax.swing.JFrame {

    /**
     * Creates new form ArduinoLCD
     */
    
    private String ss;
     PanamaHitek_Arduino ion=new PanamaHitek_Arduino();
       SerialPortEventListener lis= new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
             
          
            try {
                    if(ion.isMessageAvailable()){
                       ss=ion.printMessage();
                      // a=Integer.parseInt(ss);
                      
                       System.out.println(ss);
                      
                      // rfid.setText(ss);
                       //  jSlider1.setMaximum(1023);
                        // jSlider1.setValue(a);
                    }
                } catch (SerialPortException ex) {
                    Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ArduinoException ex) {
                    Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
                } }
    };
    public ArduinoLCD() {
        initComponents();
             try {
            ion.arduinoRXTX("COM5",9600,lis);
        } catch (ArduinoException ex) {
            Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button_arduino_OFF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        button_arduino_ON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("LED OFF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, -1));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("ARDUINO AND JAVA CONNECTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 310, -1));

        button_arduino_OFF.setBackground(new java.awt.Color(255, 255, 0));
        button_arduino_OFF.setForeground(new java.awt.Color(255, 0, 0));
        button_arduino_OFF.setText("OFF");
        button_arduino_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_arduino_OFFActionPerformed(evt);
            }
        });
        jPanel1.add(button_arduino_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 180, 40));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("LED ON");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        button_arduino_ON.setBackground(new java.awt.Color(255, 255, 0));
        button_arduino_ON.setForeground(new java.awt.Color(255, 0, 0));
        button_arduino_ON.setText("ON");
        button_arduino_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_arduino_ONActionPerformed(evt);
            }
        });
        jPanel1.add(button_arduino_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_arduino_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_arduino_OFFActionPerformed
        // TODO add your handling code here:
            //String a;
        // a = send_arduino.getText();
           try {
               ion.sendData("0");
           } catch (ArduinoException ex) {
               Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SerialPortException ex) {
               Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        
        
    }//GEN-LAST:event_button_arduino_OFFActionPerformed

    private void button_arduino_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_arduino_ONActionPerformed
        // TODO add your handling code here:
          try {
               ion.sendData("1");
           } catch (ArduinoException ex) {
               Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SerialPortException ex) {
               Logger.getLogger(ArduinoLCD.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_button_arduino_ONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArduinoLCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArduinoLCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArduinoLCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArduinoLCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArduinoLCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_arduino_OFF;
    private javax.swing.JButton button_arduino_ON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
